--EXERCÍCIO 1
SELECT 
	SUBSTRING (GRUPO_DIAGNOSTICO,3,4)
FROM
	TB_GRUPO_DIAGNOSTICO

--EXERCÍCIO 2
SELECT
	RIGHT (DESC_TIPOADMISSAO,3)
FROM
	tb_tipoadmissao

--EXERCÍCIO 3
SELECT
	LOWER (PACIENTE)
FROM
	TB_PACIENTE

--EXERCÍCIO 4
SELECT
	LEFT (DESC_TIPOADMISSAO,3)
FROM
	tb_tipoadmissao

--EXERCÍCIO 5
SELECT
	CONCAT (ESTADO,' - BR')
FROM
	TB_ENDERECO

--EXERCÍCIO 6
SELECT
	REPLACE (DESC_ESCOLARIDADE,'Colegial','Ensino Médio')
FROM
	TB_escolaridade

--EXERCÍCIO 7
SELECT * FROM TB_ENDERECO WHERE SUBSTRING (BAIRRO,5,1)='I'

SELECT * FROM TB_ENDERECO WHERE CHARINDEX ('I',BAIRRO,5)=5 ---CERTO
SELECT * FROM TB_ENDERECO WHERE CHARINDEX ('I',BAIRRO,1)=5 ---ERRADO pois está procurando a partir da posição 1

SELECT * FROM TB_ENDERECO WHERE RIGHT(LEFT(BAIRRO,5),1)='I'

--EXERCÍCIO 8
SELECT
	BAIRRO, LEN (BAIRRO)
FROM
	TB_ENDERECO

