--EXERCÍCIO 1
SELECT *
INTO
	#TIAGO_PACIENTE
FROM
	TB_PACIENTE

--EXERCÍCIO 2
SELECT TOP 100 *
INTO
	##TIAGO_PACIENTE_100
FROM
	TB_PACIENTE

SELECT * FROM ##TIAGO_PACIENTE_100

--EXERCÍCIO 3
SELECT * INTO #TIAGO_PACIENTE_2013 FROM TB_PASSAGEM WHERE DATA_ADMISSAO BETWEEN '2013-01-01 00:00:00' AND '2013-12-31 23:59:59'

SELECT * INTO #TIAGO_PACIENTE_2013_2 FROM TB_PASSAGEM WHERE YEAR(DATA_ADMISSAO)=2013

SELECT * FROM #TIAGO_PACIENTE_2013 ORDER BY DATA_ADMISSAO
SELECT * FROM #TIAGO_PACIENTE_2013_2 ORDER BY DATA_ADMISSAO

DROP TABLE #TIAGO_PACIENTE_2013

--EXERCÍCIO 4
SELECT
	PACIENTE, DT_NASCIMENTO, SEXO
INTO
	##TIAGO_PACIENTES_VERA
FROM
	TB_PACIENTE
WHERE
	PACIENTE='VERA'

SELECT * FROM ##TIAGO_PACIENTES_VERA
