--Exercício 1 - Selecione a tabela TB_ITEM e calcule a média da coluna PRECO_VENDA.
SELECT
	AVG(PRECO_VENDA) MÉDIA
FROM
	TB_ITEM

--Exercício 2 - Selecione a tabela TB_ITEM e relacione com a tabela TB_PASSAGEM_ITEM e calcule a média da coluna PRECO_VENDA quando o ano da coluna DT_LANCAMENTO for 2014.
SELECT
	AVG(TI.PRECO_VENDA) 'MÉDIA 2014'
FROM TB_PASSAGEM_ITEM TPI
	LEFT JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
WHERE
	YEAR(TPI.DT_LANCAMENTO)=2014

--Exercício 3 - Selecione a tabela TB_ITEM, relacione com TB_PASSAGEM_ITEM e TB_PASSAGEM, e calcule a média da coluna PRECO_VENDA quando o dia da coluna de DT_LANCAMENTO for Sábado.
SELECT
	AVG(TI.PRECO_VENDA) 'MÉDIA AOS SÁBADOS'
FROM TB_PASSAGEM TP
	LEFT JOIN TB_PASSAGEM_ITEM AS TPI ON TP.ID_PASSAGEM=TPI.ID_PASSAGEM
	LEFT JOIN TB_ITEM AS TI ON TPI.ID_ITEM=TI.ID_ITEM
WHERE
	DATEPART(WEEKDAY,TPI.DT_LANCAMENTO)=7
	--DATENAME(WEEKDAY,TPI.DT_LANCAMENTO)='Saturday'

--Exercício 4 - Selecione a tabela TB_PASSAGEM_ITEM, relacione com a tabela TB_ITEM e calcule a soma da coluna PRECO_VENDA quando da coluna DT_LANCAMENTO for 2016 ou 2017.
SELECT
	SUM(TI.PRECO_VENDA) 'SOMA 2016-2017'
FROM TB_PASSAGEM_ITEM TPI
	LEFT JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
WHERE
	YEAR(TPI.DT_LANCAMENTO)=2016 OR
	YEAR(TPI.DT_LANCAMENTO)=2017

--Exercício 5 - Selecione a tabela TB_PASSAGEM_ITEM e calcule a maior quantidade de 2016 (Data de lançamento).
SELECT
	MAX(QUANTIDADE) 'MAIOR QUANTIDADE'
FROM
	TB_PASSAGEM_ITEM
WHERE
	YEAR(DT_LANCAMENTO)=2016

--Exercício 6 - Selecione a tabela TB_PASSAGEM_ITEM e calcule a menor quantidade de 2015(Data de lançamento).
SELECT
	MIN(QUANTIDADE) 'QUANTIDADE MÍNIMA'
FROM
	TB_PASSAGEM_ITEM
WHERE
	YEAR(DT_LANCAMENTO)=2015

--Exercício 7 - Selecione a tabela TB_PASSAGEM_ITEM e calcule a quantidade distinta de itens utilizados em março/2017. 
SELECT DISTINCT
	COUNT(QUANTIDADE) 'QUANTIDADE DE ITENS DISTTINTOS'
FROM
	TB_PASSAGEM_ITEM
WHERE
	YEAR(DT_LANCAMENTO)=2017 AND
	MONTH(DT_LANCAMENTO)=3

--Exercício 8 - Selecione a tabela TB_ITEM, relacione com TB_PASSAGEM_ITEM e calcule a média da coluna PRECO_VENDA por ano (Data de Lançamento).
SELECT 
	YEAR(TPI.DT_LANCAMENTO) 'ANO DE LANÇAMENTO',
	AVG(TI.PRECO_VENDA) 'MÉDIA'
FROM TB_PASSAGEM_ITEM TPI
	LEFT JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
GROUP BY YEAR(TPI.DT_LANCAMENTO)
ORDER BY 'ANO DE LANÇAMENTO'

--Exercício 9 - Selecione a tabela TB_ITEM, relacione com TB_PASSAGEM_ITEM e calcule o menor PRECO_VENDA de cada mês do ano de 2015 ordenando os meses de forma crescente (Data de Lançamento). 
	SELECT 
		MONTH(TPI.DT_LANCAMENTO) 'MÊS DE LANÇAMENTO',
		MIN(TI.PRECO_VENDA) 'PREÇO MÍNIMO'
	FROM TB_PASSAGEM_ITEM TPI
		LEFT JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
	WHERE
		YEAR(TPI.DT_LANCAMENTO)=2015
	GROUP BY MONTH(TPI.DT_LANCAMENTO)
	ORDER BY 'MÊS DE LANÇAMENTO'

--Exercício 10 - Selecione a tabela TB_ITEM, TB_PASSAGEM_ITEM, TB_PASSAGEM, TB_PACIENTE e TB_ENDERECO e calcule a média do PRECO_VENDA por Estado ordenando por Estado de forma crescente.
SELECT 
	TEND.ESTADO,
	AVG(TI.PRECO_VENDA) MÉDIA
FROM TB_PASSAGEM TPASS
	INNER JOIN TB_PASSAGEM_ITEM TPI ON TPASS.ID_PASSAGEM=TPI.ID_PASSAGEM
	INNER JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
	INNER JOIN TB_PACIENTE TPAC ON TPASS.ID_PACIENTE=TPAC.ID_PACIENTE
	INNER JOIN TB_ENDERECO TEND ON TPAC.ID_PACIENTE=TEND.ID_PACIENTE
GROUP BY TEND.ESTADO
ORDER BY MÉDIA

--Exercício 11 - Selecione a tabela TB_ITEM e calcule  (média, soma, mínimo e máximo)  do PRECO_CUSTO por CATEGORIA_ITEM 
SELECT
	CATEGORIA_ITEM,
	AVG(PRECO_CUSTO) MÉDIA,
	SUM(PRECO_CUSTO) SOMA,
	MIN(PRECO_CUSTO) MÍNIMO,
	MAX(PRECO_CUSTO) MÁXIMO
FROM
	TB_ITEM
GROUP BY Categoria_item

--Exercício 12 - Selecione a tabela TB_ITEM, TB_ITEM_PASSAGEM, TB_PASSAGEM, TB_PACIENTE e TB_ESCOLARIDADE calcule a média do PRECO_VENDA por DESC_ESCOLARIDADE.  Filtrar apenas pacientes com idade maior que 50 e quando a média do PRECO_VENDA por DESC_ESCOLARIDADE for maior que 500. Ordenar por PRECO_VENDA decrescente e por ESCOLARIDADE crescente. 
SELECT
	TESC.desc_escolaridade,
	AVG(TI.PRECO_VENDA) MÉDIA
FROM TB_PASSAGEM TPASS
	INNER JOIN TB_PASSAGEM_ITEM TPI ON TPASS.ID_PASSAGEM=TPI.ID_PASSAGEM
	INNER JOIN TB_ITEM TI ON TPI.ID_ITEM=TI.ID_ITEM
	INNER JOIN TB_PACIENTE TPAC ON TPASS.ID_PACIENTE=TPAC.ID_PACIENTE
	INNER JOIN TB_escolaridade TESC ON TPAC.ESCOLARIDADE=TESC.id_escolaridade
WHERE
	CONVERT(DECIMAL(30,0),DATEDIFF(DD,DT_NASCIMENTO, GETDATE())/365.25)>50
GROUP BY TESC.desc_escolaridade
HAVING 	AVG(TI.PRECO_VENDA)>500
ORDER BY AVG(TI.PRECO_VENDA) DESC, TESC.desc_escolaridade
